source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MPIMotionKit_Example', :exclusive => true do
  pod "MPIMotionKit", :path => "../"
end

target 'MPIMotionKit_Tests', :exclusive => true do
  pod "MPIMotionKit", :path => "../"

  
end
